config/routes.rb
Rails.application.routes.draw do
  resources :patients
  resources :doctors

  
  root "patients#index"
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
      has_many :patients
           

validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
validates_format_of :phone_number, with: /\A\(?\d{3}\)?[- ]?\d{3}[- ]?\d{4}\z/  
     validates_uniqueness_of :first_name , :last_name  ,scope: [:first_name ,:last_name]


   
          def full_name 
         "#{first_name} #{last_name}"
     end
     
     
end

app/models/patient.rb
class Patient < ActiveRecord::Base
   belongs_to :doctor
validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
validates_format_of :phone_number, with: /\A\(?\d{3}\)?[- ]?\d{3}[- ]?\d{4}\z/ 

     validates_uniqueness_of :first_name , :last_name  ,scope: [:first_name ,:last_name]
   
     
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: 'Doctor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:first_name, :last_name, :license_no, :email, :phone_number)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:first_name, :last_name, :email, :phone_number, :doctor_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
    def patient_format(patient)
         "#{patient.first_name}  #{patient.last_name}   "
     end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> </h2>

      <ul>
      <% @doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name , class:"form-control"%>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name , class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :license_no %><br>
    <%= f.text_field :license_no , class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email , class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number , class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
<h1>Editing Doctor</h1>
<br>

<%= render 'form' %>
<br>
<%= link_to 'Show', @doctor , class:"btn btn-info"%> |
<%= link_to 'Back', doctors_path , class:"btn btn-info"%>
</div>
  <div class="col-md-4"></div>
</div>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Doctors</h1>

<table>
  <table class="table table-hover">
  <thead>
    <tr>
     
      <th>License no</th>
      
      <th colspan="3"> Patient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.license_no %></td>
         <td>
          <%  doctor.patients.each do |patient| %>
          <%= patient_format(patient) %>
          <br>
          <%end%>
          </td>
        <td><%= link_to 'Show', doctor, class:"btn btn-warning" %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) , class:"btn btn-info" %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path  , class:"btn btn-danger" %>

app/views/doctors/new.html.erb
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
<h1>New Doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path , class:"btn btn-info" %>
</div>
  <div class="col-md-4"></div>
</div>

app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @doctor.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @doctor.last_name %>
</p>

<p>
  <strong>License no:</strong>
  <%= @doctor.license_no %>
</p>

<p>
  <strong>Email:</strong>
  <%= @doctor.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%=number_to_phone( @doctor.phone_number) %>
</p>
<br>
       <table class="table table-bordered">
       
          <strong>Patients information </strong>
          
       <thead>
       <tr>
        <th>first name</th>
        <th>last name</th>
        <th>email</th>
        <th>phone number</th>
        </tr>
        </thead>
        <tbody>
        <% @doctor.patients.each do |a|%>
        <tr>
        <td> <%= a.first_name%></td>
        <td>  <%= a.last_name%></td>
        <td>  <%= a.email%></td>
        <td>   <%= number_to_phone( a.phone_number) %></td>
        </tr>
        </tbody>
           
        
        <% end %>

       </table>
       
<%= link_to 'Edit', edit_doctor_path(@doctor) , class:"btn btn-primary btn-sm" %> |
<%= link_to 'Back', doctors_path , class:"btn btn-primary btn-sm" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>application</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <ul class="nav nav-pills">
  <li role="presentation" ><a href="https://first-application-ahmed007.c9users.io/patients">Patient</a></li>
  <li role="presentation"><a href="https://first-application-ahmed007.c9users.io/doctors">Doctor</a></li>
</ul>
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-7">
<%= yield %>
</div>
  <div class="col-md-2"></div>
</div>
</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> </h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name , class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name , class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email , class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number , class:"form-control" %>
  </div>
  <div class="field">
    <%= f.label :doctor_id %><br>
    <%= f.select( :doctor_id, Doctor.all.collect {|p| [ p.first_name, p.id ] }, { include_blank: true }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
<h1>Editing Patient</h1>

<%= render 'form' %>
<br>
<%= link_to 'Show', @patient , class:"btn btn-info" %> |
<%= link_to 'Back', patients_path , class:"btn btn-info" %>
</div>
  <div class="col-md-4"></div>
</div>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Patients</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      
            <th colspan="3">Doctor</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.first_name %></td>
        <td><%= patient.last_name %></td>
       
        <td><%= patient.doctor.first_name %></td>
        <td><%= link_to 'Show', patient  , class:"btn btn-warning" %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) , class:"btn btn-info" %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path , class:"btn btn-danger" %>

app/views/patients/new.html.erb
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
<h1>New Patient</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', patients_path , class:"btn btn-info" %>
</div>
  <div class="col-md-4"></div>
</div

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @patient.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @patient.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @patient.email %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= number_to_phone( @patient.phone_number) %>
</p>
<p>
  <strong>Doctor information</strong>
 
 <br>
 
    <%= @patient.doctor.first_name %>,
    <%= @patient.doctor.last_name %>,
    <%= @patient.doctor.email %>,
    <%= number_to_phone(@patient.doctor.phone_number) %>
      
     <br>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) , class:"btn btn-primary btn-sm" %> |
<%= link_to 'Back', patients_path , class:"btn btn-primary btn-sm" %>